### ISSUE TITLE
Rejection not caught in PoolMaster._flushErrors

### ISSUE THREAD

**Issue by mbroadst** [neumino/rethinkdbdash#110]
https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L94

On this line the promise is rejected but never caught leading to the following error output:

```
Possibly unhandled ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
```
followed by a huge stack trace

There is no way for the user to hook into this error, and no way to silence it

**Comment by neumino** [comment]
I'm not sure that his error is in the driver. Do you have the stacktrace for this error?

If a pool becomes empty, all the queries that are waiting for a connection from this pool will be rejected. We push handlers here: 
https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L126
And the driver uses `_line` only for `getConnection`, and we always have an error handler when `getConnection` is called.

**Comment by mbroadst** [comment]
The stack trace is on the line I linked above, I can include the full trace if you'd like but I wanted to keep any company specific details out of the issue. To be clear, it's not an actual error, it's that you reject that promise (on the line linked above) and have nothing that actually catches it, as far as I can tell.

I'm able to get this error to occur immediately when adding an invalid/unreachable server to my configuration for rethinkdbdash (or thinky for that fact, since it just forwards it).

**Comment by neumino** [comment]
Typically if you do run this script and kill rethinkdb just after, I believe you will see this error
```
var r = require('./lib/index.js')({ // rethinkdbdash for RethinkDB 2.1
  max: 1,
});

r.js('while (true) {}').run();
r.js('while (true) {}').run();
```
This is because the second queries doesn't have an error handler.

Theses [rejections](https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L94) are called with [_flushErrors](https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L92). The property `_line` is just a queue and the place where we push something inside is in [getConnection](https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L126).

`getConnection` is called in a few places by the driver
- In [run](https://github.com/neumino/rethinkdbdash/blob/master/lib/term.js#L143) where it bubbles up the error to the promise return by `run`.
- In [getConnection](https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L108) where we just loop over all healthy pools
- In the `new-connection` [handler](https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L290) where it does bind a error listener (the one given in getConnection.

So `getConnection` always bubbles up the errors to the promise returned by `run`. The driver runs a query only when discovery is `true` [here](https://github.com/neumino/rethinkdbdash/blob/master/lib/pool_master.js#L149) and does bind an error handler.

The only place left where this could happen is if the user call `run` and doesn't add an error handler.

**Comment by mbroadst** [comment]
Please run this code and tell me what _you_ see on the command line, just to make sure I'm not going crazy here:

```
var thinky = require('thinky')({
  host: 'this.totally.does.not.exist',
  port: 28015,
  db: 'some-non-existant-db',
  timeoutError: 5000,
  silent: true
});

var Test = thinky.createModel('test', {
  name: thinky.type.string()
});
```

**Comment by mbroadst** [comment]
Or is the implication that createModel should have an error handler attached to it?

**Comment by neumino** [comment]
Oh I see, this is actually a bit more complicated and is a thinky issue. I opened https://github.com/neumino/thinky/issues/289 to discuss more about that. Basically when you call createModel, we return a model. not a promise even though we do run a few queries to create the table and indexes. I thought about returning a promise, but it makes using thinky quite painful.

The current behavior in case we fail to create the table/indexes is kind of undefined. We catch the error in a few places but not everywhere. The intended behavior was to throw an error and let the process crash (I think). We may want to change that.
