### ISSUE TITLE
Trapping Connection Errors

### ISSUE THREAD

**Issue by weshoke** [neumino/rethinkdbdash#123]
When a connection is lost, I get a stream of these errors.  I'd like to be able to trap them and log them through my own system as opposed to having them end up on the console.  The Rethink driver has a connection.on("error", ...) event.  Is there a way to do this with rethinkdbdash?

```
ReqlDriverError: Failed to connect to localhost:28015
Full error:
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect"
}.
    at Socket.<anonymous> (../node_modules/rethinkdbdash/lib/connection.js:89:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickDomainCallback (node.js:381:11)
From previous event:
    at r.connect ../node_modules/rethinkdbdash/lib/index.js:78:11)
    at Pool.createConnection (../node_modules/rethinkdbdash/lib/pool.js:177:18)
    at null._onTimeout (../node_modules/rethinkdbdash/lib/pool.js:279:14)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by weshoke** [comment]
It would also be nice to be able to get events when a connection has been made again so that things like change feeds can be restarted.

**Comment by neumino** [comment]
Short answer: Not at the moment

Longer answer: Some background on why the driver write on stderr
- I think it's common practice to have errors dumped on stderr - at least I do, so I find it more convenient if the driver can do it itself without having me binding a listener
- Some people have been complaining about that especially during development as it's not super nice hence the `silent` option.

I rewrote a decent chunk of code related to the pools/connections for RethinkDB 2.1. I'll add (try to add) the following things in 2.1.0 (or in 2.1.1):
- Dump errors in stderr by default and have the option to silent errors on stderr (like we do now)
- Let users bind a listener for the `msg` event on `r` (or `r.getPoolMaster`) such that they can redirect things if needed. It's going to be `msg` or something else besides `error` since if we emit errors, it means that the users have to explicitly handle them while they don't. The driver can recover by itself.

**Comment by neumino** [comment]
Ok, just pushed that on the branch `raft` that will be released with RethinkDB 2.1.

You can basically pass `silent: true` to avoid the driver writing on stderr. The messages that were logged on `stderr` are also available via the pool master:
```
r.getPoolMaster().on("log", function(message) {
  // do something with message
});
```

**Comment by neumino** [comment]
Relevant commit: 7a1f12046a4957aee78cb393c38ed5ecb5cd8b24

**Comment by neumino** [comment]
In 2.1

**Comment by astanciu** [comment]
I have a similar question, not sure how to resolve this. 

If I have a connection pool and my server dies, how can I catch that event gracefully and take action from there? Would be great if there was some event emitted when this happened. 

Is there some other method I can detect when the server is down/backup?

**Comment by neumino** [comment]
This is currently not available, mostly because the driver automatically recovers by itself.

The driver could probably emit events when we add/remove a pool from `_heathyPools` I guess.

**Comment by astanciu** [comment]
So if I wanted to implement a feature where if the db goes down, all queries that clients keep sending would be buffered for example, is there another way to know when that happens? Is `_healthyPools` a counter I can check for a zero value maybe?
