### ISSUE TITLE
Pool creation logs to console.error

### ISSUE THREAD

**Issue by LordRalex** [neumino/rethinkdbdash#143]
When a pool is created, a message is logged saying it is being created.

However, this logs to console.error, which is incorrectly used in the case here as this is not an error.
In our application, we have a wrapper around the console logging functions so that we can log them into a file and have a consistent view, but rethinkdbdash does not use the console correctly in this case.

```
[2015-08-25 14:14:44] [ERROR] Creating a pool connected to localhost:28015
```

We tracked it down to the following stack, which shows where the call was being made.
```
    at Pool._log (/cifs/share/PufferPanel/node_modules/rethinkdbdash/lib/helper.js:10:15)
    at new Pool (/cifs/share/PufferPanel/node_modules/rethinkdbdash/lib/pool.js:58:8)
    at new PoolMaster (/cifs/share/PufferPanel/node_modules/rethinkdbdash/lib/pool_master.js:60:12)
    at r.createPools (/cifs/share/PufferPanel/node_modules/rethinkdbdash/lib/index.js:85:22)
    at main (/cifs/share/PufferPanel/node_modules/rethinkdbdash/lib/index.js:530:34)
```

This type of message should not be logged to error as it is not an error, but an info message.

**Comment by neumino** [comment]
The main reason why the pool master logs everything on `stderr` is because it blows to look for connections in `stdout` and disconnections in `stderr`. It's a pain to replay what happened -- if you actually have to debug something.

Anyway, you can just pass the `silent` argument and listen for `log` events on the pool master if you want to redirect the output.
https://github.com/neumino/rethinkdbdash#connection-pool

**Comment by LordRalex** [comment]
So, in the scope of logs, everything is considered the same level. Is there going to be any way to track if a log is an error or not? Or any 'hack' to achieve that then? I do want to have logs from rethinkdbdash being shown on the console, but I would like to mark such logs when they are displayed as the correct 'level' (i.e info, error).

**Comment by neumino** [comment]
You can run a regex against the log messages...

```
r.getPoolMaster().on('log', console.log);
```

**Comment by DaneEveritt** [comment]
So instead of just logging things to the correct level, you are just logging everything as an error, and expecting users to have to sort through every message that comes through (many of which we don't even know exist) and decide if they are an error or not, and then re-route those as we see?

That seems like a terrible design.

**Comment by neumino** [comment]
The design is to log everything at the same level. If you don't want to do that, you are free to log them any level you want.
