### ISSUE TITLE
Move to bluebird 3

### ISSUE THREAD

**Issue by neumino** [neumino/rethinkdbdash#170]
There are a few non backward compatible changes. The main one being that calling `Promise.reject` does not automatically create an operational error.
After a bit of tweaking, there seem to be more things to do, not sure what exactly.

**Comment by mbroadst** [comment]
@neumino it's not too hard, I fixed this on my fork by cleaning up the errors [here](https://github.com/mbroadst/rethunk/blob/master/lib/error.js) and then switching the cases where you generally do `.error(function() { ... })` with a `.catch(errors.ReqlBaseError, function() { ... })`.

IIRC that was all that was required. Optionally, you could have your errors inherit bluebird's OperationalError but I find the solution above to be far more explicit (since you are indeed looking for particular types of errors)

**Comment by neumino** [comment]
Thanks @mbroadst for the tip. I went the long way and manually set errors as operational to prevent non compatible change.

Fixed in 2.1.13

**Comment by neumino** [comment]
Actually it's 2.1.14
