### ISSUE TITLE
How to change default database?

### ISSUE THREAD

**Issue by adius** [neumino/rethinkdbdash#212]
As I don't have access to the connection, how can I easily change the default database after initialization?

**Comment by neumino** [comment]
```
var r = require('rethinkdbdash')({
  db: 'foo'
})
```

**Comment by adius** [comment]
AFTER initialization

**Comment by marshall007** [comment]
@adius I don't think there's a way to change the default database across all connections in the pool. For a single query you can specify the `db` optarg to `run` like so: `r.table('foo').run({ db: 'bar' })`. You could also just reinitialize `rethinkdbdash`.

**Comment by adius** [comment]
Thanks @marshall007 !
What are the drawbacks of reinitialization?

**Comment by neumino** [comment]
My bad, like @marshall007 said, you can't change the default database after having initialized rethinkdb.
This is because the default database is tied to a connection, not a pool. This is the official API.
If we allow people to change the default database, we would have to overwrite the default database for all connections which can be tricky since we don't always have a reference to all of them.

If you reinitialize rethinkdbdash, you basically create a new connection pool. What's your use case behind switching the default database?

**Comment by aleclarson** [comment]
> What's your use case behind switching the default database?

Calling `dbCreate`, then switching to the new database.

**Comment by neumino** [comment]
@aleclarson - You can connect with the default database, create the default database, and then run your queries.

**Comment by aleclarson** [comment]
Like this?

```js
const rethinkdb = require('rethinkdbdash');
const r = rethinkdb({ host, port, db: 'foo' });
r.dbCreate('foo').run().then(() => {
  return r.tableCreate('bar').run();
});
```

This works because the default database is not referenced until a query has its `run` method called without a `db` option, right?

**Comment by neumino** [comment]
Yes.
This works because the default database (here `foo`) is not relevant in the first query (`dbCreate`)
