### ISSUE TITLE
Nested insert following query disappears

### ISSUE THREAD

**Issue by jordanh** [neumino/rethinkdbdash#280]
Hiya Michel –

We are huge fans of rethinkdbdash, it is indispensable to [our project](https://github.com/ParabolInc/action).

We noticed something peculiar today, and we're not sure if it's a bug or a known limitation. Also not sure where the logic exists to process ReQL query strings here within rethinkdbdash or if it's within in rethinkdb itself. Here's the poop... 💩 

We wrote a query which nested an insert statement inside of a `do()` following a query, like this:

```javascript
const dbWork = r.table('TeamMember')
      // get number of users
        .getAll(teamId, {index: 'teamId'})
        .filter({isActive: true})
        .count()
        // get the user
        .do((usersOnTeam) => ({
          usersOnTeam,
          user: r.table('User').get(userId)
        }))
        // insert team member
        .do((teamCountAndUser) => {
          r.table('TeamMember').insert({
            checkInOrder: teamCountAndUser('usersOnTeam').add(1),
            id: teamCountAndUser('user').add('::', teamId),
            teamId,
            userId,
            isActive: true,
            isLead: false,
            isFacilitator: false,
            picture: teamCountAndUser('user')('picture'),
            preferredName: teamCountAndUser('user')('preferredName'),
          });
          return teamCountAndUser('user')('email');
        })
```

If we explore what happens when this query is sent to the server using the `toString()` method, we'll see it'll look like this:

```javascript
r.table("TeamMember").getAll("Hkp2fYq5", {
    index: "teamId"
}).filter({
    isActive: true
}).count().do(function(var_9) {
    return {
        usersOnTeam: var_9,
        user: r.table("User").get("auth0|57bd08feeae095471ab98746")
    }
}).do(function(var_10) {
    return var_10("user")("email")
});
```

Note that the insert statement disappeared! If we hand-roll this ReQL and drop it into the Data Explorer, it works. So, we were a bit confused.

We can work around this by chaining the insert statement like this:

```javascript
      const dbWork = r.table('TeamMember')
      // get number of users
        .getAll(teamId, {index: 'teamId'})
        .filter({isActive: true})
        .count()
        // get the user
        .do((usersOnTeam) => ({
          usersOnTeam,
          user: r.table('User').get(userId)
        }))
        // insert team member
        .do((teamCountAndUser) =>
          r.table('TeamMember').insert({
            checkInOrder: teamCountAndUser('usersOnTeam').add(1),
            id: teamCountAndUser('user')('id').add('::', teamId),
            teamId,
            userId,
            isActive: true,
            isLead: false,
            isFacilitator: false,
            picture: teamCountAndUser('user')('picture').default(''),
            preferredName: teamCountAndUser('user')('preferredName').default(''),
          }).do(() =>
            // ...but return the user's email
            teamCountAndUser('user')('email')
          )
        )
```

Questions: is this intentional (i.e. a limitation we're unaware of) or perhaps a bug? If it's a bug, does it belong here or with rethinkdb?

**Comment by marshall007** [comment]
It actually surprises me that your original query actually works in the Data Explorer. I would imagine this is just a quirk in how the Data Explorer parses queries rather than intentional behavior. @jordanh have you tried running the query in Node using the official JS driver? I doubt it would work there either.

Your second query (using another `.do()` after the insert) is the correct way to write this query. Any nested expressions that are not returned will be ignored. Notice if you try something like this (even in the Data Explorer), it will complain:

```js
r.expr({}).do(() => {
  r.table('data').insert({ foo: 'bar' })
  return undefined
})
// -> Error: Anonymous function returned `undefined`. Did you forget a `return`?
```

**Comment by marshall007** [comment]
By the way, when I ran your original query in the Data Explorer the `insert` expression was omitted as expected. I'm curious to know whether or not you were actually able to perform the insert without returning it from the nested block.

You should be able to run something like this in the Data Explorer to confirm you're seeing the same behavior:

```js
var query = r.expr({}).do(data => {
  r.table('data').insert({ foo: 'bar' });
  return data;
}).toString();

r.expr(query)
```

**Comment by neumino** [comment]
I don't have much to add to what @marshall007 said. I doubt this actually work with the official driver or the data explorer.

To shed a bit of light on why the insert is drop, consider this query:

```
r.expr(1).do(function(value) {
  r.table('foo').insert({bar: 2});
  return 4
})
```

The driver is going to parse `r.expr(1)`, then hit `do` and find a function. It will replace `value` with a reql term (what you see as `var_<X>` when you call `toString`).
From there, we are going to build the term `r.table('foo').insert({bar: 2})` (but not execute it), and because we just return 4, we just drop the term for the insert.

There's more information here:
- How to write a driver: http://rethinkdb.com/docs/writing-drivers/
- Demystify ReQL anynomous function: http://www.rethinkdb.com/blog/lambda-functions/

**Comment by jordanh** [comment]
Upon rechecking, you were correct – the insert is dropped. We may have misinterpreted our own test in the heat of battle.

Thank you so much for your considered responses! I'm sure others will benefit from this thread.
