### ISSUE TITLE
Log messages are displayed as errors

### ISSUE THREAD

**Issue by smashercosmo** [neumino/rethinkdbdash#292]
Can't understand, why normal logs (not errors) are also displayed as errors with {silent: false}? It's really strange to have "Creating a pool connected to localhost:28015" in your console displayed as an error.

**Comment by neumino** [comment]
Because if you print some messages on STDOUT, and some STDERR, it's a pain to understand what actually happened.

**Comment by smashercosmo** [comment]
@neumino sorry, I can't understand your explanation ((( why again only errors can't be output as errors? Why "it's a pain to understand what actually happened"? Could you provide some example?

**Comment by neumino** [comment]
Because if you log successful connection to STDOUT, and disconnections to STDERR, then you need to look at both logs to know the state of your pool (connected or not).

If you disagree with how things are logged, you can pass `silent: true` and use the `log`  event on the pool master.
https://github.com/neumino/rethinkdbdash#connection-pool
