### ISSUE TITLE
Is there a way to catch connection errors?

### ISSUE THREAD

**Issue by mshi** [neumino/rethinkdbdash#316]
Hi,

Sometimes I see errors like these `Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to localhost:28015 in less than 20s.","isOperational":true}`. However, these are not present in the failure callbacks. Is there a way to catch these such that I know which queries failed?

**Comment by MarkusPint** [comment]
+1 Random connection errors occur. Should be a way to handle those.

**Comment by neumino** [comment]
No the driver doesn't bubble up these errors back to the user because there's nothing the user can do to handle them. The pool will automatically recover if RethinkDB is available again.

You can still run a query, but they will fail with a network error message. The `healthy` event on the pool master tells you whether your request are going to be immediately rejected or not.
