### ISSUE TITLE
Convert variable declarations inside ReQL functions into r.do

### ISSUE THREAD

**Issue by thelinuxlich** [neumino/rethinkdbdash#66]
Because if I do a var foo = expensive_reql_operation(); and reuse it many times, the driver will call the expensive_reql_operation many times too. I don't know if this is viable because of the coerceTo("type")  thing.

**Comment by neumino** [comment]
This is not possible (as far as I know) for a few reasons:
- We cannot overload `=` in JavaScript, so you cannot guess when someone wrote `foo = expensive_reql_operation`. I guess coercing a function to a string and then parsing it may work, but it's error prone.
- This is basically about where to declare variable. It's an optimization problem, and I while it could be possible to move things one level out if nothing depends on the local scope, it's again hard and tricky to do.
It's also sometimes not possible if there are some non deterministic commands.

If the expensive operation can be computed once, it's more or less the responsibility of the developer to do it now. It may not be the case later, but this is something the server should do, not the driver (since there are many things only the server knows about).

Closing for now as I don't see how this is technically possible. If you have a precise idea on how to do it, let me know :)
