### ISSUE TITLE
Way to turn off automatically running queries in promises

### ISSUE THREAD

**Issue by thejsj** [neumino/rethinkdbdash#78]
One of my favorite features of ReQL is the ability to modify a query and then pass it along to another query. 

```
query = r.table('table');
query = query.count();
```
This is really nice when you want to append something to a query. 
```
query = r.table('table');
if (something) query = query.fields({ something: false });
```
Then problem with rethinkdbdash is that you can't do this with promises because when you return a query it automatically runs itself ([See code](https://github.com/neumino/rethinkdbdash/blob/master/lib/term.js#L2628-L2639)). 

```
q()
.then(function () {
  return r.table(); 
})
.then(function (query) { // Imagining this returns the query and not the results of the query
 return query.filter({ something: 'something' });
});
```

Although I understand the reason for this feature and think it's cool, is there a way in which something can be implemented for this feature to be turned off? To get a bit more context, is this by design or just an unintended consequence of the convenience provided by modifying these methods? If this sounds like a terrible suggestion, it can be completely ignored :).

Currently, I forked it and just commented out those lines.

**Comment by marshall007** [comment]
I think this is just an (unintended?) side-effect of the [1.16.0 release](https://github.com/neumino/rethinkdbdash/releases/tag/v1.16.0) which made `r.table(...).then(...)` an alias to `r.table(...).run().then(...)`. I think this is going to be tricky to fix since bluebird tries to treat any object with a `then` method as if it were a promise ([see implementation](https://github.com/petkaantonov/bluebird/blob/d762c987b75913937866b16fd59646d0acc25186/src/thenables.js#L31)).

**Comment by neumino** [comment]
This is an intended behavior. For 1.16 I just wrote examples using generators because it was more shiny, but the idea is the same for with normal promises.

While it's true that you can "fork" queries in rethinkdbdash and in the official driver, you can't really fork them in promises. For example you can use `query` here just one if you tackle a `then` at the end.
```
var p = promise.then(function(result) {
    var query = buildQuery(result) // the query depends on the result
    return query;
})
```
If you do `p.then`, the fullfilled handler will be called with result, not query.

If you don't plan on forking the query, then there is no reason to not merge the two fullfilled handler.

On a side note, if you really want to remove this functionality, you can do
```
var r = require('rethinkdbdash')();
r._Term.prototype.then = undefined;
```
But to me it sounds like something is wrong in your code if you absolutely need it, or maybe I'm missing a use case?

**Comment by thejsj** [comment]
@neumino @marshall007 Thanks for responding. I mostly just interested to see in how other people do this and how others go about it. 

I'll go ahead and close the issue, since it seems like this is not an unintended consequence and more of a deliberate (perhaps opinionated :)) decision.

@neumino I don't really get what you mean by this: 

> If you don't plan on forking the query, then there is no reason to not merge the two fulfilled handler.

From what I'm understanding, you're suggesting I turn this: 
```
q()
.then(function () {
  return r.table(); 
})
.then(function (query) { // This has no asynchronous operations, but it could easily have some! 
  if (Math.random() > 0.5) {
    return query.filter({ something: 'something' });
  }
  return query;
});
```
Into: 
```
q()
.then(function () {
  var query = r.table(); 
  if (Math.random() > 0.5) {
    query = query.filter({ something: 'something' });
  }
});
```
If that's the case, that's a valid suggestion but I really like the elegance of being able to create different handlers for different parts of a dynamically generate query. When there are 3-4 possible parts of a query that can be dynamically generated, separating them into different handlers make it easier to read and understand what's going on. This also makes creating dynamic queries based on asynchronous operations easier. All that being said, this is mostly personal taste.

For the time being, I'll just stick to a combination `r._Term.prototype.then = undefined;`, my fork, or the original RethinkDB driver. 

@neumino Thanks for the awesome driver!
